### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by chengdonglin** [blake-regalia/shmmap.js#1]
the following error:

 memory.cpp
  win_delay_load_hook.cc
e:\electron_project\tmapconvertsdk\x64\node_modules\shmmap\src\memory.cpp(6): fatal error C1083: 无法打开包括文件: “sys/mman.h”: No such file or directory [E:\e
lectron_p
roject\TMAPConvertSDK\x64\node_modules\shmmap\build\shmmap.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\nvm\v8.11.2\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "E:\\nodejs\\node.exe" "E:\\nvm\\v8.11.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\electron_project\TMAPConvertSDK\x64\node_modules\shmmap
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN x64@1.0.0 No description
npm WARN x64@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shmmap@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shmmap@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chengdong\AppData\Roaming\npm-cache\_logs\2019-03-15T13_27_29_652Z-debug.log

**Comment by blake-regalia** [comment]
Need help implementing POSIX Shared Memory equivalent for Windows.
